### ISSUE TITLE
Latest Updates broken

### ISSUE THREAD

**Issue by lionslair** [antonioribeiro/countries-laravel#11]
Just did a composer update and the latest update appears to have broken things.

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Container.php line 767:
                                                                  
  Class PragmaRX\Countries\Package\Services\Cache does not exist  

It's in the PragmaRX\Countries package. I cleared my composer cache reinstalled all and still occurs.

**Comment by d1am0nd** [comment]
Same issue here

**Comment by lionslair** [comment]
I reverted my composer.lock file and that got things working again. 

If you manually make that change in the config file does it work?

Changelog says to see the countries change log but that doesn't say to update the config file.

https://github.com/antonioribeiro/countries/blob/master/CHANGELOG.md

If that is what needs updating why not put it in this packages changelog?

**Comment by lionslair** [comment]
If you replace with this

` 'service' =>  PragmaRX\Countries\Package\Services\Cache\Service::class,`

The install works

**Comment by lionslair** [comment]
I created a PR to update the changelog

https://github.com/antonioribeiro/countries-laravel/pull/12

**Comment by antonioribeiro** [comment]
Just added the info to it

**Comment by antonioribeiro** [comment]
@lionslair, just merged yours, it had some more good information, thanks a lot!
