### ISSUE TITLE
 Package pragmarx/countries-laravel at version  has a PHP requirement incompatible with your PHP version (5.6.23)

### ISSUE THREAD

**Issue by sagunraj** [antonioribeiro/countries-laravel#15]

**Comment by eliasjtg** [comment]
![image](https://user-images.githubusercontent.com/22435698/48862788-5498a500-ed95-11e8-9bcd-514158b82ca4.png)

**Comment by antonioribeiro** [comment]
Yeah, not compatible with 5.6 anymore, sorry.
