### ISSUE TITLE
Can't install on Laravel 7

### ISSUE THREAD

**Issue by vezlius** [antonioribeiro/countries-laravel#20]
There is an error when installing on Laravel 7:

```
Problem 1
    - Conclusion: remove nesbot/carbon 2.31.0
    - Conclusion: don't install nesbot/carbon 2.31.0
    - pragmarx/ia-collection v5.5.33 requires nesbot/carbon ~1.20 ->
```

**Comment by nessimabadi** [comment]
laravel-shift

**Comment by stefanocurnis** [comment]
not working for me as well..

**Comment by blindsz** [comment]
I also have issues installing this on laravel 7

**Comment by pixelplant** [comment]
Opened 20 days ago, no response, all for a simple change in the composer.json of another required package. Guess we'll have to fork 4 different packages in order to make this work...

**Comment by Skullbock** [comment]
@pixelplant gonna use your forks for now, thanks :)

**Comment by pixelplant** [comment]
@Skullbock 
You'd also need to define all the other repos in your project's composer.json
```
"repositories":[
        {
            "type": "vcs",
            "url": "https://github.com/pixelplant/countries-laravel.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/pixelplant/coollection.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/pixelplant/countries.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/pixelplant/ia-arr.git"
        }
    ],
```
It still wouldn't work though because of all the other dependencies in the other projects. To be honest we only use the countries list and in 1 place only so we'll completely remove this package from our list and create a table and model that holds this data, this way we remove a whole bunch of dependencies for our project.

**Comment by Skullbock** [comment]
@pixelplant yeah i did exactly that and still didn't work.
Unfortunate though. I hoped to PR the fix here but it seems the dependency tree is just to messy.

Thanks anyway

**Comment by antonioribeiro** [comment]
@pixelplant , You went all the way down to create a lot of forks to fix it, but I don't see any Pull Requests to fix those packages, sorry, but why?

Updating them to really work with everything for whole ecosystem is not as simple as bumping some versions on composer.json.

Take a look at these commits:

https://github.com/antonioribeiro/ia-collection/commits/master
https://github.com/antonioribeiro/ia-str/commits/master
https://github.com/antonioribeiro/ia-arr/commits/master
https://github.com/antonioribeiro/coollection/commits/master

But it's done. 

Thank you.
