### ISSUE TITLE
Unable to publish configuration file

### ISSUE THREAD

**Issue by bilfeldt** [antonioribeiro/countries-laravel#5]
According to documentation, then it should be possible to publish the packages config file using

`php artisan vendor:publish --provider=PragmaRX\Countries\ServiceProvider`

But no configuration file is generated.

Clearing the cache with `php artisan config:clear` does not seem to fix the issue nor does `php artisan cache:clear`

I am currently testing on Laravel 5.5 (and I am using this repository in composer: "pragmarx/countries-laravel": "^0.5.2")

**Comment by antonioribeiro** [comment]
Sorry the readme was wrong, this is the correct command:

```
php artisan vendor:publish --provider=PragmaRX\\CountriesLaravel\\Package\\ServiceProvider
```

Every time you have problems with publishing in Laravel you can do this:

![image](https://user-images.githubusercontent.com/3182864/37484516-82ff4a8c-2867-11e8-9ac6-81dd422663b8.png)

And just hit the number of the ServiceProvider you need to publish

**Comment by bilfeldt** [comment]
Thank you for quick feedback. This solved the issue. I will for sure use this next time.
